require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PrestadoresController do

  # This should return the minimal set of attributes required to create a valid
  # Prestador. As you add validations to Prestador, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PrestadoresController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all prestadores as @prestadores" do
      prestador = Prestador.create! valid_attributes
      get :index, {}, valid_session
      assigns(:prestadores).should eq([prestador])
    end
  end

  describe "GET show" do
    it "assigns the requested prestador as @prestador" do
      prestador = Prestador.create! valid_attributes
      get :show, {:id => prestador.to_param}, valid_session
      assigns(:prestador).should eq(prestador)
    end
  end

  describe "GET new" do
    it "assigns a new prestador as @prestador" do
      get :new, {}, valid_session
      assigns(:prestador).should be_a_new(Prestador)
    end
  end

  describe "GET edit" do
    it "assigns the requested prestador as @prestador" do
      prestador = Prestador.create! valid_attributes
      get :edit, {:id => prestador.to_param}, valid_session
      assigns(:prestador).should eq(prestador)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Prestador" do
        expect {
          post :create, {:prestador => valid_attributes}, valid_session
        }.to change(Prestador, :count).by(1)
      end

      it "assigns a newly created prestador as @prestador" do
        post :create, {:prestador => valid_attributes}, valid_session
        assigns(:prestador).should be_a(Prestador)
        assigns(:prestador).should be_persisted
      end

      it "redirects to the created prestador" do
        post :create, {:prestador => valid_attributes}, valid_session
        response.should redirect_to(Prestador.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved prestador as @prestador" do
        # Trigger the behavior that occurs when invalid params are submitted
        Prestador.any_instance.stub(:save).and_return(false)
        post :create, {:prestador => {}}, valid_session
        assigns(:prestador).should be_a_new(Prestador)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Prestador.any_instance.stub(:save).and_return(false)
        post :create, {:prestador => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested prestador" do
        prestador = Prestador.create! valid_attributes
        # Assuming there are no other prestadores in the database, this
        # specifies that the Prestador created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Prestador.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => prestador.to_param, :prestador => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested prestador as @prestador" do
        prestador = Prestador.create! valid_attributes
        put :update, {:id => prestador.to_param, :prestador => valid_attributes}, valid_session
        assigns(:prestador).should eq(prestador)
      end

      it "redirects to the prestador" do
        prestador = Prestador.create! valid_attributes
        put :update, {:id => prestador.to_param, :prestador => valid_attributes}, valid_session
        response.should redirect_to(prestador)
      end
    end

    describe "with invalid params" do
      it "assigns the prestador as @prestador" do
        prestador = Prestador.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Prestador.any_instance.stub(:save).and_return(false)
        put :update, {:id => prestador.to_param, :prestador => {}}, valid_session
        assigns(:prestador).should eq(prestador)
      end

      it "re-renders the 'edit' template" do
        prestador = Prestador.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Prestador.any_instance.stub(:save).and_return(false)
        put :update, {:id => prestador.to_param, :prestador => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested prestador" do
      prestador = Prestador.create! valid_attributes
      expect {
        delete :destroy, {:id => prestador.to_param}, valid_session
      }.to change(Prestador, :count).by(-1)
    end

    it "redirects to the prestadores list" do
      prestador = Prestador.create! valid_attributes
      delete :destroy, {:id => prestador.to_param}, valid_session
      response.should redirect_to(prestadores_url)
    end
  end

end
